sudo: false
language: python
os: linux
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

before_install:
  - pip install poetry

install:
  - pip install tox-travis coverage

script:
  - tox
  - coverage combine

after_success:
  - bash <(curl -s https://codecov.io/bash)
