sudo: false
language: python
os: linux
dist: xenial
python:
  # - 3.9
  # - 3.8
  # - 3.7
  - 3.6

env:
  - EXTRA_INSTALLS="pandas matplotlib bokeh plotly kaleido weasyprint beautifulsoup4"
  - EXTRA_INSTALLS=""

install:
  - pip install pytest coverage $EXTRA_INSTALLS

script:
  - coverage run --append --source esparto -m pytest

jobs:
  include:
  - python: "3.8"
    script:
    - pip install black flake8 mypy
    - black esparto tests --check
    - flake8 esparto tests
    - mypy esparto tests
    - python -m tests.check_package_version

after_success:
  - bash <(curl -s https://codecov.io/bash)
