sudo: false
language: python
os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  # - 3.10 # Not currently available on travis

env:
  - EXTRA_INSTALLS=""
  - EXTRA_INSTALLS="Pillow ipython pandas matplotlib bokeh plotly kaleido weasyprint<53 beautifulsoup4 html5lib"

install:
  - pip install . pytest coverage $EXTRA_INSTALLS

script:
  - coverage run --append --source esparto -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
