sudo: false
language: python
os: linux
dist: xenial
python:
  - 3.9
  # - 3.8
  # - 3.7
  # - 3.6

before_install:
  - pip install poetry

install:
  - poetry install --no-dev -E test

jobs:
  include:
  - stage: test-min-deps
    script:
    - black --check .
    - flake8
    - coverage run --source esparto -m pytest
    - ls -la
  - stage: test-max-deps
    script:
    - poetry install -v
    - black --check .
    - flake8
    - coverage run --source esparto -m pytest
    - ls -la

after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)
