sudo: false
language: python
os: linux
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

env:
  - INSTALL_DEPS=""
  - INSTALL_DEPS="--no-dev"

before_install:
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
  - python get-poetry.py -y
  - export PATH="$PATH:$HOME/.poetry/bin"
  - poetry config virtualenvs.in-project true

install:
  - poetry install $INSTALL_DEPS
  - pip install pytest coverage

script:
  - coverage run --append --source esparto -m pytest

jobs:
  include:
  - python: "3.8"
    script:
    - pip install black flake8 mypy
    - black esparto tests --check
    - flake8 esparto tests
    - mypy esparto tests
    - python -m tests.check_package_version

after_success:
  - bash <(curl -s https://codecov.io/bash)
