language: python
os: linux
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

env:
  - INSTALL_FLAGS=""
  - INSTALL_FLAGS="--no-dev"

before_install:
  - pip install poetry

install:
  - poetry install $INSTALL_FLAGS

script:
  - black --check .
  - flake8
  - COVERAGE_FILE=".coverage${INSTALL_FLAGS}"
  - coverage run --source esparto -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
