language: python
os: linux
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - black --check .
  - flake8
  - mypy esparto tests
  - COVERAGE_FILE=".coverage.${TRAVIS_JOB_NUMBER}"
  - coverage run --source esparto -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
