sudo: false
language: python
os: linux
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

before_install:
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
  - python get-poetry.py -y
  - export PATH="$PATH:$HOME/.poetry/bin"
  - poetry config virtualenvs.in-project true

install:
  - poetry install --no-dev -E test

jobs:
  include:
  - stage: test-min-deps
    script:
    - black --check .
    - flake8
    - coverage run --append --source esparto -m pytest
  - stage: test-max-deps
    script:
    - poetry install -v
    - black --check .
    - flake8
    - coverage run --append --source esparto -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
