sudo: false
language: python
os: linux
dist: xenial
python:
  - 3.9
  # - 3.8
  # - 3.7
  # - 3.6

install:
  - pip install poetry coverage

jobs:
  include:
  - stage: test-min-deps
  - script:
    - poetry install -v --no-dev -E test
    - poetry run coverage run --append --module pytest
    - ls -la
  - stage: test-max-deps
  - script:
    - poetry install -v -E test
    - poetry run coverage run --append --module pytest
    - ls -la

after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)
