site_name: esparto
theme:
  name: material
  icon:
    logo:
      material/file
  palette:
    primary: 'teal'
    accent: 'cyan'
  features:
    - 'navigation.tabs'
    - 'navigation.sections'
    - 'toc.integrate'

repo_url: 'https://github.com/domvwt/esparto/'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      toc_depth: 2

nav:
  - Overview: 'index.md'
  - User Guide:
        - 'Quick Start': '02-user-guide/quick-start.md'
        - 'Output Options': '02-user-guide/output-options.md'
        - 'Tutorial Notebooks': '02-user-guide/tutorial-notebooks.md'
  - API Reference:
        - 'Layout': '03-api-reference/layout.md'
        - 'Content': '03-api-reference/content.md'
        - 'Options': '03-api-reference/options.md'
        - 'Publish': '03-api-reference/publish.md'
        - 'Adaptors': '03-api-reference/adaptors.md'
  - About:
        - 'Authors': '04-about/authors.md'
        # - 'Contributing': '04-about/contributing.md'
        - 'Release Notes': '04-about/release-notes.md'
        # - 'Roadmap': '04-about/roadmap.md'
        - 'License': '04-about/license.md'

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
        handlers:
              python:
                    rendering:
                          show_root_heading: True
                          show_root_toc_entry: False
                          show_root_full_path: False
                    selection:
                          inherited_members: False

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dominic-thorn/
      name: LinkedIn
    - icon: fontawesome/solid/address-card
      link: https://domvwt.github.io/
      name: domvwt | portfolio
